server:
  port: 8089
  error:
    path: /error

logging:
  level:
    root: ${LOGGING_LEVEL:TRACE}

spring:
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    grade-center:
      url: ${GRADE_CENTER_URL:jdbc:postgresql://localhost:5433/grade-center-db}
      username: ${GRADE_CENTER_USERNAME:postgres}
      password: ${GRADE_CENTER_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

springframework:
  boot:
    autoconfigure:
      security:
        - category: INFO