server:
  port: 8089
  # Error path to handle errors
  error:
    path: /error

logging:
  level:
    root: ${LOGGING_LEVEL:TRACE}

spring:
  thymeleaf:
    # Disable cache when developing which will not require restart when changes are made
    cache: false
  web:
    resources:
      add-mappings: false
  mvc:
    # Create custom 404 handler
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  #    database: mysql
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true
  datasource:
    grade-center:
      url: ${GRADE_CENTER_URL:jdbc:postgresql://localhost:5433/grade-center-db}
      username: ${GRADE_CENTER_USERNAME:postgres}
      password: ${GRADE_CENTER_PASSWORD:postgres}
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect

# Spring security log
org:
  springframework:
    boot:
      autoconfigure:
        security:
          - category: INFO